### PR TITLE
rust: Generate documentations

### PR DESCRIPTION
**Pull request by zhaofengli**
This makes the IDE/editor experience *slightly* more tolerable :stuck_out_tongue:

Example: https://gitcdn.link/cdn/mars-research/pal/bd9fe2ed938178efeca215dfe25a0b0dbb03b294/pal/vmcs/vm_exit_controls/index.html

### CODE REVIEW

**Comment by JaredWright** [comment]
Ooo... I'm very excited to review this one. The _result_ of these changes looks amazing! There's a few tweaks that probably need to happen in the _how_ this gets accomplished though. I'll leave a full review for tomorrow with some detailed thoughts.

**Review by JaredWright — CHANGES_REQUESTED** [review]
Overall, this is awesome! The PR gets to the core of what this project is all about: making it less painful to program against giant PDF manuals. Let me know if you'd like to chat more about my suggested changes, or if things can't work the way I'm describing for some reason.

**Comment by zhaofengli** [comment]
Sorry for the delay, and thanks for the review! I've made `declare_{file,item}_documentation` abstract methods in `CommentWriter` and added dummy implementations for them in other writers.

While we are doing this, would it make sense for us to have `declare_{file,item}_documentation`'s default implementations simply concatenate the text and call `declare_comment`? As the next step, we can then move the related `declare_comment` calls in the code generators call `declare_{file,item}_documentation` instead where they semantically make sense. Assuming comments can be declared anywhere in the code, nothing should break.

**Review by JaredWright — APPROVED** [review]

**Comment by JaredWright** [comment]
I think thats a really good idea to replace all of the existing calls to `declare_comment` in all of the generators with things that semantically make sense relative to documentation. It might make sense to review those changes in their own PR, and instead implement a real C/C++ documentation format (maybe doxgen? something better?). I'll open an issue for this in the project backlog!

**Pull request merged**
